### ISSUE TITLE
Will this be ever added to the apache compiler ?

### ISSUE THREAD

**Issue by EMCP** [twitter/ios-twitter-apache-thrift#2]
**Is your feature request related to a problem? Please describe.**

This looks very much what I need for calling thrift services from within mac OS apps.. I just was curious if it's possible to ever see this officially included in the Apache Thrift project itself?

Big thanks for releasing this!

**Comment by EMCP** [comment]
ah I just read this

```
The implementation of these models deviate from the official thrift specification. The official specification was designed for languages without automatic encoding and decoding. Output and input binary will be up to the official thrift specification. 
```

Does this mean if I have an Apache Thrift Python Server.. this Swift code cannot talk to it .. darn

**Comment by jay18001** [comment]
> This looks very much what I need for calling thrift services from within mac OS apps.. I just was curious if it's possible to ? ever see this officially included in the Apache Thrift project itself?

In theory that's possible. That would be up to Twitter.

> Does this mean if I have an Apache Thrift Python Server.. this Swift code cannot talk to it .. darn

That should work but you'll have to write your own networking. We designed this to encode the thrift data then we put it as the body of an http request.
