### ISSUE TITLE
Need help rolling package into an XCode MacOS App

### ISSUE THREAD

**Issue by EMCP** [twitter/ios-twitter-apache-thrift#3]
**Is your feature request related to a problem? Please describe.**

I have a helloworld-ish MacOS app based off the XCode 13.x , targeting MacOS 12.x+

https://stackoverflow.com/questions/72895796/having-trouble-with-adding-a-swift-package-to-macos-app/72898864#72898864

So far I can just clone the repo and switch to a release tag and load it locally.. but ideally I think the instructions on how to do this properly or in a more connected way would be helpful

**Describe the solution you'd like**

Hear how to roll this package into a Mac OS Swift App, in order to call a thrift server from a MacOS Application in Swift

**Comment by jay18001** [comment]
You should be able to just add the package in Xcode `File->Add Packages`

**Comment by EMCP** [comment]
i worked around the issue, so I will close.. but when I did Add Packages it failed .. if I can I will retry in future if needed
